### ISSUE TITLE
Cannot read property 'Symbol(toStringTag)' of undefined for 

### ISSUE THREAD

**Issue by Jaans** [aurelia/polyfills#10]
The new Aurelia polyfills is erroring out when a `null` or `undefined` value is passed for the `Object.prototype.toString` polyfill.

![image](https://cloud.githubusercontent.com/assets/3510981/13573724/c5a576f8-e4cc-11e5-86cc-189e5c2d853a.png)

I found the source usage that is receiving the above Aurelia error inside the `momentjs` library where it checks input using the `Object.prototype` (see screenshot below):
![image](https://cloud.githubusercontent.com/assets/3510981/13573812/22d69622-e4cd-11e5-8ca7-dca912aec576.png)

Let me know if you need more info.

**Comment by EisenbergEffect** [comment]
We have a fix coming.

**Comment by NateRedding** [comment]
I got this error as well. I think the core.js library has the same issue also. When I tried importing core-js  from main.js, I get the same error message, but a different stacktrace (obviously).

**Comment by mthomson** [comment]
I rolled back to core-js and this error has gone away.  I'm putting the core-js client right into index.html

**Comment by EisenbergEffect** [comment]
Putting core-js in the index.html is probably the easiest way to ensure that it works correctly. We do have a fix for this particular issue coming shortly.

**Comment by damianof** [comment]
How can we update our packages references without getting this latest patch? It seems this start from aurelia-bootstrapper which is the one who has a reference to the aurelia-polyfills

**Comment by EisenbergEffect** [comment]
Fixed. Release coming shortly.

**Comment by damianof** [comment]
Thank you Bob.

**Comment by damianof** [comment]
Ok now there is no more errors, but the application no longer renders.

**Comment by paranoxx** [comment]
For me, its working fine now.

**Comment by damianof** [comment]
paranoxx, did you try cleaning everything, node modules, jspm packages, dist, and start from scratch with npm install, then jspm update then gulp build?

**Comment by paranoxx** [comment]
No, why should i?

**Comment by Jaans** [comment]
Excellent! Issue fixed. 
Thank you for the quick turnaround.

**Comment by damianof** [comment]
paranoxx, you should not, but if you do you'll experience my issue. This might be unrelated to this issue, and I'm currently still trying to figure out which other updates to which other aurelia package is causing this. I only know that my app was working fine until the last 2-3 days.

**Comment by paranoxx** [comment]
Shoudn't you do a jspm install -y after a clean?

**Comment by damianof** [comment]
paranoxx You should not have too. I usually never do jspm install -y. Let me dig a little more into my config and see what I can find. I' put together a little solution with a subset and I'll post on github public shortly

**Comment by paranoxx** [comment]
I'm not that into the internals of jspm but that's what i do while preparing deployment.
Checkout project on destination server, npm install followed by jspm install -y followed by gulp bundle.

**Comment by damianof** [comment]
paranoxx all seems working again in my sandbox here https://github.com/damianof/aurelia-config-samples

**Comment by leosbrf** [comment]
Should that fix also cover null values? I'm getting a similar error when null.
