### ISSUE TITLE
Aurelia polyfills are enumerable

### ISSUE THREAD

**Issue by jods4** [aurelia/polyfills#12]
When you simply assign the prototype, like so: 
`Array.prototype.includes = function...`
You introduce a new enumerable member for all arrays.

So if someone had written code like this:
```javascript
for (var i in myArray) {
  var v = myArray[i];
  // do whatever with v
}
```

It's very likely to now break, because `"includes"` will be an iteration of `i`.

This is a regression wrt previous releases that used corejs. I didn't check but I guess that CoreJs defines a non-enumerable property for its polyfills.

**Comment by EisenbergEffect** [comment]
Well, you shouldn't use a for/in loop with an array ;) But, we'll get it fixed.

**Comment by jods4** [comment]
I was sure you would say that. :wink: 

I don't approve but I'm not the only committer to our code base...
FWIW, this was considered common enough that recently the TS team has taken special steps to support this pattern...

**Comment by EisenbergEffect** [comment]
We'll fix it. I'm looking at it now. No problem :)

**Comment by jods4** [comment]
Reading my comment above I realize it was ambiguous... For the record I don't approve the practice of `for..in` over arrays, not your comment ;)

Just sayin': a quick glance over the code shows that `string.js` has the same problem, although it's certainly a lot less likely to trigger issues. I know of noone who does `for (var i in "troll")`.

**Comment by EisenbergEffect** [comment]
Yeah, I understood your meaning :) I fixed the array issues but wasn't sure if it was worth it to fix the string issues. It's not that big a deal though. I could do it.
