### ISSUE TITLE
Uncaught TypeError: Cannot read property 'Symbol(toStringTag)' of null

### ISSUE THREAD

**Issue by stoffeastrom** [aurelia/polyfills#13]
When loading babel-core@5.8.35/browser.js it will throw this exception [here](https://github.com/aurelia/polyfills/blob/master/src/symbol.js#L251) since it's being called with `null`

For development I configured

```javascript
System.config({
  defaultJSExtensions: true,
  transpiler: "babel",
  babelOptions: {
    "optional": [
      "es7.decorators",
      "es7.classProperties"
    ],
    "sourceMaps": "inline"
  },
```
and get this error

**Comment by EisenbergEffect** [comment]
So, checking this for null or undefined should do the trick right? Would you be interested to submit a PR for that? @stoffeastrom

**Comment by stoffeastrom** [comment]
Yes that should be sufficient. Just stumbled on this. I will see if I can get it up and running. If so it should be fast fixing a PR

**Comment by EisenbergEffect** [comment]
I can release it almost immediately if you send a PR :)

**Comment by PWKad** [comment]
Confirmed this is same issue from earlier

**Comment by stoffeastrom** [comment]
If I can do it via my phone :). Just need to get my kids sleeping then I'll look into it
