### ISSUE TITLE
Reflect.getOwnMetadata gets metadata for parents

### ISSUE THREAD

**Issue by cehoffman** [aurelia/polyfills#18]
Reflect.getOwnMetadata lacks a check for `target.hasOwnProperty(metadataContainerKey)` and so will erroneously return the metadata from the parent prototype.

I discovered this when switching to the use this polyfill instead of core-js and one of my test cases on metadata exposure through class inheritance failed.

**Comment by EisenbergEffect** [comment]
We would love it if you could submit a PR to fix the issue :)
