### ISSUE TITLE
No Reflect.ownKeys polyfill

### ISSUE THREAD

**Issue by graemechristie** [aurelia/polyfills#28]
Current Reflect polyfill does not contain the ownKeys method.

I'm currently using the martingust/aurelia-repeat-strategies plugin (https://github.com/martingust/aurelia-repeat-strategies), which makes use of Reflect.ownKeys

Either I can submit a PR for the ownKeys polyfill to this repo (which is simply)

```
if (typeof Reflect.ownKeys !== 'function')
    Reflect.ownKeys = function (o) {
    return (Object.getOwnPropertyNames(o).concat(Object.getOwnPropertySymbols(o))));
}
```

Or I can submit a PR to martin's repo replacing his call to ownKeys with the above.

Do you have any preference ?

**Comment by EisenbergEffect** [comment]
Please submit a PR to this repo. Thanks for catching this!

**Comment by graemechristie** [comment]
No worries, PR inbound !
