### ISSUE TITLE
List what polyfills are included

### ISSUE THREAD

**Issue by Gheoan** [aurelia/polyfills#37]
**I'm submitting a feature request**

**Current behavior:**
Source code must be checked to find what polyfills are included in this library.

**Expected/desired behavior:**
* **What is the expected behavior?**
There should be a list of what polyfills are included in this library.

* **What is the motivation / use case for changing the behavior?**
Only loading missing polyfills when using other polyfills libraries besides this one.

**Comment by EisenbergEffect** [comment]
@Gheoan Sounds like a great contribution opportunity to send a PR to the readme file :)

**Comment by Gheoan** [comment]
- `Array.from`
- `Array.prototype.find`
- `Array.prototype.findIndex`
- `Array.prototype.includes`
- `WeakMap`
- `Map`
- `Set`
- `WeakSet`
- `Number.isNaN`
- `Number.isFinite`
- `Object.keys`
- `Object.assign`
- `Reflect.getOwnMetadata`
- `Reflect.defineMetadata`
- `Reflect.metadata`
- `Reflect.defineProperty`
- `Reflect.construct`
- `Reflect.ownKeys`
- `String.prototype.endsWith`
- `String.prototype.startsWith`
- `Object.getOwnPropertySymbols`
- `Symbol`

**Comment by Gheoan** [comment]
PR ready: https://github.com/aurelia/polyfills/issues/38.
