### ISSUE TITLE
Add Promise support?

### ISSUE THREAD

**Issue by lygstate** [aurelia/polyfills#40]
**I'm submitting a feature request**

* **Browser:**
all |  Qt

**Current behavior:**

* **What is the motivation / use case for changing the behavior?**
Promise can be implement in small piece of codes. (200 lines of code?)

**Comment by EisenbergEffect** [comment]
We're not planning to implement promise support directly in the polyfill. Modern browsers support this and there are very solid external libraries that are better to use than what we could build. Also, some module loaders come with Promises included. Same thing goes with some other polyfill libraries, so we don't want step all over that.
