### ISSUE TITLE
Regarding polyfill.io

### ISSUE THREAD

**Issue by jack4it** [aurelia/polyfills#42]
Question: Have we tested Aurelia using polyfill.io? Is polyfill.io an compatible option for Aurelia?

**Comment by EisenbergEffect** [comment]
We have't tested it but you should be able to map aurelia-polyfills to another library or url.

**Comment by jack4it** [comment]
Cool. I'll try and report back

**Comment by JakeChampion** [comment]
Hi, polyfill.io contributor here 👋 - We currently don't have any polyfills for `Reflect`, we are happy to accept PRs to add them. I believe we have all the other polyfills that are inside this repository :-)
