### ISSUE TITLE
Support Object.create(null) targets

### ISSUE THREAD

**Issue by jdanyow** [aurelia/polyfills#43]
When target is `Object.create(null)`, `Reflect.defineMetadata` and `Reflect.getOwnMetadata` throw:

>TypeError: target.hasOwnProperty is not a function

Running samples: [reflect-metadata](https://runkit.com/58545c03cdd70f001461b254/58545c03cdd70f001461b255) vs [aurelia-polyfills](https://runkit.com/58545c03cdd70f001461b254/58545d8150e51d001481536d)

```js
require("aurelia-polyfills");

var obj = {};
Reflect.defineMetadata('foo', 'test value 1', obj);
console.info(Reflect.getOwnMetadata('foo', obj)); // test value 1

obj = Object.create(null);
Reflect.defineMetadata('foo', 'test value 2', obj);  // TypeError: target.hasOwnProperty is not a function
console.info(Reflect.getOwnMetadata('foo', obj)); // TypeError: target.hasOwnProperty is not a function
```

**Comment by jdanyow** [comment]
todo: uncomment this line once this issue is fixed-

https://github.com/aurelia/metadata/pull/48/files#diff-0ded15bd8569583909126bfa08b23b3dR39

**Comment by Alexander-Taran** [comment]
Same behavior with 1.3.0
Is it still relevant?

**Comment by Alexander-Taran** [comment]
@bigopon mumbo-jumbo javascript.. do we still need this issue?
