### ISSUE TITLE
IE 11 issue - still get "Access Denied" in getOwnPropertyNames

### ISSUE THREAD

**Issue by matik12** [aurelia/polyfills#44]
**I'm submitting a bug report**

* **Library Version:**
aurelia-polyfills@1.1.1

* **Browser:**
IE 11 - 11.672.10586.0

* **Language:**
TypeScript 2.1 

**Current behavior:**
After adding [Power Bi](https://github.com/Microsoft/PowerBI-JavaScript) which creates an iframe underneath, I can still see following errors in console multiple times:
```js
SCRIPT5: Access is denied.
aurelia-polyfills.js (131,7)
```
[![PowerBi.png](https://s29.postimg.org/wzmu8xbnb/Power_Bi.png)](https://postimg.org/image/rbgji17ar/)

This is simple repro project using power bi client library. First install dependencies npm i and then run app i.e. gulp watch. PowerBi token can expire, so please obtain new one -> more info in **src/powerbi.ts** file.
[Polyfills-Repro.zip](https://github.com/aurelia/polyfills/files/716238/Polyfills-Repro.zip)

**Comment by EisenbergEffect** [comment]
@jdanyow Any chance you can look into this?

**Comment by jdanyow** [comment]
https://github.com/zloirock/core-js/issues/76

**Comment by jdanyow** [comment]
@EisenbergEffect do you think we should update our polyfills to fix this issue?

https://github.com/zloirock/core-js/issues/76

https://github.com/paulmillr/es6-shim/commit/cee098d1cb451540e1e8f5341180964bbb66c66d

**Comment by EisenbergEffect** [comment]
Seems like it. Any idea if it's a small fix?

**Comment by genachka** [comment]
+1
Same as @mikeesouth noted on #22, we're not seeing this in current releases of Chrome or Firefox. Only on IE 11 (we're using 11.0.9600.18617) 100% of the time as well.

Any updates on this?

**Comment by magnusdanielson** [comment]
I just noticed @doubleaa93 made the PR, I will skip my PR. Sorry for the delay.

**Comment by jp7677** [comment]
Thanks a lot @doubleaa93! Any chance to get this PR merged soon?

**Comment by EisenbergEffect** [comment]
We'll get it out this week :)

**Comment by jp7677** [comment]
@EisenbergEffect Thans a lot!

**Comment by EisenbergEffect** [comment]
Merged fix. Releasing in a few minutes.
