### ISSUE TITLE
async ... await ... does not work under IE

### ISSUE THREAD

**Issue by tomicse** [aurelia/polyfills#45]
Hi
problem is, if it is used, comes Exception

ERROR [app-router] TypeError: Object.getOwnPropertyNames: az argumentum nem objektum
[object Error]{description: "Object.getO...", message: "Object.getO...", name: "TypeError", number: -2146823281, stack: "TypeError: ..."}

**Comment by StrahilKazlachev** [comment]
Can you provide more info why you think `aurelia-polyfills` is at wrong and how?
`async await` is a new syntax and as such can not be polyfilled, it is transpiled, so what are you using for that - babel, ts, ...?
