### ISSUE TITLE
Stackoverflow Exception in IE10

### ISSUE THREAD

**Issue by Cedware** [aurelia/polyfills#49]
**I'm submitting a bug report**

* **Library Version:**
1.2.1

**Please tell us about your environment:**
* **Operating System:**
Windows 7

* **Node Version:**
7.3.0

* **NPM Version:**
4.0.3

* **JSPM OR Webpack AND Version**
webpack 2.5.1

* **Browser:**
IE 10
* **Language:**
TypeScript 2.3.2

Hello,
The library causes a stackoverflow exception with Internet Explorer 10, I will attach a screenshot of the piece of code where the exception occurs.
If I deleted the content of the aurelia-poyfills.js and used core-js instead to make sure it's not a failure caused by me.
Until this is fixed is there a way to stop aurelia from using the polyfills?

![image](https://cloud.githubusercontent.com/assets/13673693/26498227/9b085b84-422e-11e7-80ed-18b360dacd82.png)

Regarding to the developer console the error is caused at this line:
`if (!this || this.constructor !== Collection) return new Collection(a);`

Thanks

Cedric

**Comment by EisenbergEffect** [comment]
You can always map aurelia-polyfills to a different library or an empty module.

**Comment by JoseRoman** [comment]
Any plans on a fix for this?

**Comment by waywardz** [comment]
This also impacts ie11.  #821

**Comment by EisenbergEffect** [comment]
No PR in over a year, so closing. Anyone who encounters similar issues, please consider using an alternative polyfill.
