### ISSUE TITLE
propertyIsEnumerable null reference exception in IE 11

### ISSUE THREAD

**Issue by sludemann** [aurelia/polyfills#50]
**I'm submitting a bug report**

* **Library Version:**
1.2.1

**Please tell us about your environment:**
* **Operating System:**
Windows 10

* **Node Version:**
6.3.1

* **NPM Version:**
3.10.3

* **JSPM OR Webpack AND Version**
webpack 2.2.1

* **Browser:**
IE 11

* **Language:**
ESNext

**Current behavior:**
Using `ag-grid` we're consistently getting the following exception in IE 11 when onGetRows fires:
![image](https://user-images.githubusercontent.com/2914538/26837029-6078d352-4aaa-11e7-8665-466f4be207fb.png)

**Expected/desired behavior:**
No null reference exception appears.

In `symbol.js` change propertyIsEnumberable to this:
```
propertyIsEnumerable = function propertyIsEnumerable(key) {
      var uid = '' + key;
      return onlySymbols(uid) ? (
        hOP.call(this, uid) &&
        this[internalSymbol] &&
        this[internalSymbol]['@@' + uid]
      ) : pIE.call(this, key);
    }
```
I'd be happy to submit the PR, but am unfamiliar with your process.

**Comment by EisenbergEffect** [comment]
We welcome your PR. Don't worry about the process too much for the first time. You'll be asked to sign the CLA and we may want to edit the commit title. We can walk you through that after you submit, if needed. Thanks!

**Comment by tborres** [comment]
This fixes our issue with the usage of `Symbol` in IE11, and appears to be a pretty straightforward null check. What steps are needed to get this merged in? It would be great to get this in the next version as I'm currently hotfixing in the node_modules, but I know that's eventually going to burn me (is that why it's called a hotfix?)

**Comment by EisenbergEffect** [comment]
Merged fix. Releasing in a few minutes.
