### ISSUE TITLE
Symbol is not defined in Firefox 35

### ISSUE THREAD

**Issue by unional** [aurelia/polyfills#53]
**I'm submitting a bug report**

* **Library Version:**
1.2.1

**Please tell us about your environment:**
* **Operating System:**
Linux

* **Browser:**
Firefox 35

* **Language:**
all

**Current behavior:**
`Symbol is not defined` at https://github.com/aurelia/polyfills/blob/master/dist/aurelia-polyfills.js#L277
src: https://github.com/aurelia/polyfills/blob/master/src/symbol.js#L277

**Expected/desired behavior:**
It should be polyfilled.

**Comment by gheoan** [comment]
It is polyfilled by the code you linked.

**Comment by unional** [comment]
The line I linked throw exception `Symbol is not defined` on FireFox 35. 
And also, if you look into the code. It does not use the pass in param `S`. 

The issue is accessing `Symbol` immediately throws. Need to be something like `window['Symbol']`

**Comment by Alexander-Taran** [comment]
An firefox 35 is special how?
I thought the were evergreen.

**Comment by unional** [comment]
It's about the range of browsers supported. Somewhere in between, this code doesn't work.

See https://stackoverflow.com/questions/45453374/should-in-between-browser-compatibility-issue-be-handled for more details.

**Comment by Alexander-Taran** [comment]
Ok.. so you are the guy who's been asked to support FF35..
As in answer to your question on SO - say no.
IE is different in a way. For corporations that buit internal software for IE6. 
Firefox.. no reason to support that far back.

**Comment by EisenbergEffect** [comment]
Closing for now. Happy to accept a PR if there's a legitimate fix and it's still needed.
