### ISSUE TITLE
I'd like to add Object.values polyfill

### ISSUE THREAD

**Issue by chdev77** [aurelia/polyfills#54]
Using Object.values on IE 11 throws an error.
_'Unhandled rejection TypeError: Object doesn't support property or method 'values''_

I'd like to see something similar added, or at least make note of it.

const valuesPolyfill = function values (object) {
  return Object.keys(object).map(key => object[key]);
};

**Comment by gronostajo** [comment]
According to repository's description, this library is *"The minimal set of polyfills needed to run Aurelia."* `Object.values` is super-useful, but I don't think it fits `aurelia-polyfills`.

By the way, take a look at [existing polyfills for `Object.values`](https://developer.mozilla.org/pl/docs/Web/JavaScript/Reference/Global_Objects/Object/values#Polyfill). They are more complex than what you proposed.

**Comment by EisenbergEffect** [comment]
My recommendation is that if you need that, find a suitable modularlized polyfill for just this feature and add it to your project. We want to be careful not to add more polyfills than Aurelia itself actually needs to run in older browsers.
